print("Meu primeiro projeto versionado com Git!")
print("Estou aprendendo Git e GitHub.")
print("Agora estou entendendo a Staging Area.")
print("Esta alteração vai entrar no Stage.")
print("Agora estou conectado ao GitHub.")
